---
detected: true  # bool - required
template_filename: "cpp_exe.cpp.template" # string - required
language: "cpp" # string - required
filetype: "exe" # string - required
description: "Allocates memory for shellcode by creating a new heap, memcpy shellcode into it and then creates a pointer to the buffer and calls it"